# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/hyper/8ea9fa30-44d1-426f-b2c3-a08ad9d0dc58/Projects/HyperEngine-Reworked

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/hyper/8ea9fa30-44d1-426f-b2c3-a08ad9d0dc58/Projects/HyperEngine-Reworked

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/hyper/8ea9fa30-44d1-426f-b2c3-a08ad9d0dc58/Projects/HyperEngine-Reworked/CMakeFiles /run/media/hyper/8ea9fa30-44d1-426f-b2c3-a08ad9d0dc58/Projects/HyperEngine-Reworked//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/hyper/8ea9fa30-44d1-426f-b2c3-a08ad9d0dc58/Projects/HyperEngine-Reworked/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HyperEngine

# Build rule for target.
HyperEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HyperEngine
.PHONY : HyperEngine

# fast build rule for target.
HyperEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/build
.PHONY : HyperEngine/fast

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_impl_glfw.o: include/imgui/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/imgui_impl_glfw.o

# target to build an object file
include/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/imgui_impl_glfw.cpp.o

include/imgui/imgui_impl_glfw.i: include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.cpp.i

include/imgui/imgui_impl_glfw.s: include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.cpp.s

include/imgui/imgui_impl_opengl3.o: include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.o

# target to build an object file
include/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/imgui_impl_opengl3.cpp.o

include/imgui/imgui_impl_opengl3.i: include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.cpp.i

include/imgui/imgui_impl_opengl3.s: include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/engine/Application.o: src/engine/Application.cpp.o
.PHONY : src/engine/Application.o

# target to build an object file
src/engine/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Application.cpp.o
.PHONY : src/engine/Application.cpp.o

src/engine/Application.i: src/engine/Application.cpp.i
.PHONY : src/engine/Application.i

# target to preprocess a source file
src/engine/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Application.cpp.i
.PHONY : src/engine/Application.cpp.i

src/engine/Application.s: src/engine/Application.cpp.s
.PHONY : src/engine/Application.s

# target to generate assembly for a file
src/engine/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Application.cpp.s
.PHONY : src/engine/Application.cpp.s

src/engine/Window.o: src/engine/Window.cpp.o
.PHONY : src/engine/Window.o

# target to build an object file
src/engine/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Window.cpp.o
.PHONY : src/engine/Window.cpp.o

src/engine/Window.i: src/engine/Window.cpp.i
.PHONY : src/engine/Window.i

# target to preprocess a source file
src/engine/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Window.cpp.i
.PHONY : src/engine/Window.cpp.i

src/engine/Window.s: src/engine/Window.cpp.s
.PHONY : src/engine/Window.s

# target to generate assembly for a file
src/engine/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/engine/Window.cpp.s
.PHONY : src/engine/Window.cpp.s

src/glad/glad.o: src/glad/glad.c.o
.PHONY : src/glad/glad.o

# target to build an object file
src/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/glad/glad.c.o
.PHONY : src/glad/glad.c.o

src/glad/glad.i: src/glad/glad.c.i
.PHONY : src/glad/glad.i

# target to preprocess a source file
src/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/glad/glad.c.i
.PHONY : src/glad/glad.c.i

src/glad/glad.s: src/glad/glad.c.s
.PHONY : src/glad/glad.s

# target to generate assembly for a file
src/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/glad/glad.c.s
.PHONY : src/glad/glad.c.s

src/sandbox/main.o: src/sandbox/main.cpp.o
.PHONY : src/sandbox/main.o

# target to build an object file
src/sandbox/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/sandbox/main.cpp.o
.PHONY : src/sandbox/main.cpp.o

src/sandbox/main.i: src/sandbox/main.cpp.i
.PHONY : src/sandbox/main.i

# target to preprocess a source file
src/sandbox/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/sandbox/main.cpp.i
.PHONY : src/sandbox/main.cpp.i

src/sandbox/main.s: src/sandbox/main.cpp.s
.PHONY : src/sandbox/main.s

# target to generate assembly for a file
src/sandbox/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HyperEngine.dir/build.make CMakeFiles/HyperEngine.dir/src/sandbox/main.cpp.s
.PHONY : src/sandbox/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HyperEngine"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_impl_glfw.o"
	@echo "... include/imgui/imgui_impl_glfw.i"
	@echo "... include/imgui/imgui_impl_glfw.s"
	@echo "... include/imgui/imgui_impl_opengl3.o"
	@echo "... include/imgui/imgui_impl_opengl3.i"
	@echo "... include/imgui/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/engine/Application.o"
	@echo "... src/engine/Application.i"
	@echo "... src/engine/Application.s"
	@echo "... src/engine/Window.o"
	@echo "... src/engine/Window.i"
	@echo "... src/engine/Window.s"
	@echo "... src/glad/glad.o"
	@echo "... src/glad/glad.i"
	@echo "... src/glad/glad.s"
	@echo "... src/sandbox/main.o"
	@echo "... src/sandbox/main.i"
	@echo "... src/sandbox/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

